version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    environment:
      - ENV=production
      - PORT=8081
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=shop
      - JWT_SECRET=${JWT_SECRET:-change_this_prod_secret}
      - FRONTEND_URL=${FRONTEND_URL:-https://findest.uz,http://findest.uz,https://tss.findest.uz,http://tss.findest.uz,https://134.209.218.206,http://134.209.218.206,http://134.209.218.206:5174}
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - uploads-data:/data/uploads
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=/
    environment:
      - VITE_API_BASE=/
    command: ["npm","run","build"]
    volumes:
      - frontend-build:/app/dist

  frontend_preview:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=http://134.209.218.206:8081
    environment:
      - VITE_API_BASE=http://134.209.218.206:8081
    depends_on:
      - backend
    ports:
      - "5174:5174"
    command: ["npm","run","preview","--","--host","--port","5174"]
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - frontend-build:/usr/share/nginx/html:ro
      - certbot-webroot:/var/www/certbot:ro
      - letsencrypt:/etc/letsencrypt
volumes:
  mongo-data: {}
  frontend-build: {}
  certbot-webroot: {}
  letsencrypt: {}
  uploads-data: {} 